### ISSUE TITLE
Broken backward compatibility on TLS certs

### ISSUE THREAD

**Issue by erik-frontify** [blackknight36/puppet-bacula#17]
The latest changes to master broke the backward compatibility as it now overwrites the TLS cert files and keys with the puppet once. At least if the files were put into the default locations.

**Comment by blackknight36** [comment]
Sorry about that.  You may want to set your puppetfile to use the v2.0.9 tag until this is addressed.  I can add a parameter to control use of the puppet certs however I believe it makes sense to use them by default since the node is already running puppet any way.

**Comment by erik-frontify** [comment]
Easy, I just switched back to my local branch. As in the latest tag there are my changes missing.

Besides that I'm using the puppet certs anyways. Just through my profile which gave me a duplicate definition as the same file is defined within my profile and the module, now.

I just wanted to avoid that it is overwriting the files for someone who's not using puppet certs....

**Comment by blackknight36** [comment]
> I just wanted to avoid that it is overwriting the files for someone who's not using puppet certs....

I'm not even sure how many people use this module to be honest.  :D

I suppose something like a `use_puppet_certs` parameter would make sense as there is also a `tls_ca_cert_dir` parameter which would cause conflicts if somebody were to use that option.

**Comment by erik-frontify** [comment]
Yes, sounds absolutely reasonable. I would even go for enabling that by default for new users and just allowing legacy users to disable it for backward compatibility.

**Comment by blackknight36** [comment]
One other thing I just thought of is that this issue only affects bacula *clients*.  The director and storage certificates are still unmanaged by puppet although by default the director is a client of itself which means you will still end up with the same certificate in the end.

In the end it would probably make things easier to have certificate management done in a different class so that director, storage, and client nodes can just include it.

**Comment by erik-frontify** [comment]
Yes, I've just seen that I manage the certs on all bacula related services using the puppet certificates (through my "profiles" module). So a different class or a switch sounds good to me.

**Comment by blackknight36** [comment]
This should be resolved in the master branch now.  By default all services will use the puppet certificates, to avoid this the `use_puppet_certs` parameter must be set to false.

**Comment by erik-frontify** [comment]
Yes, I can second that.
I've to add these three keys to hiera and it works as expected:
bacula::client::use_puppet_certs: false
bacula::storage::use_puppet_certs: false
bacula::director::use_puppet_certs: false

**Comment by blackknight36** [comment]
That's good to hear.  I'm going to mark this as resolved.
