### ISSUE TITLE
Would you mind tagging this module?

### ISSUE THREAD

**Issue by erik-frontify** [blackknight36/puppet-bacula#4]
As I'm using the module through github directly and not through puppet labs, I'd like to ask you if you could create a tag for every version (like v2.0.8).

**Comment by blackknight36** [comment]
No problem.  I'm not using the forge for this module either so having tags wouldn't be a bad idea.

**Comment by blackknight36** [comment]
I just created a tag for v2.0.9 which contains the latest commits.

**Comment by erik-frontify** [comment]
Cool, thanks!
